print('Tabuada')

n = int(input('Informe qual Valor deseja ver a tabuada: '))
print('-' * 18)
print('0  x ',n, ' = {:2}'.format(n*0))
print('1  x ',n, ' = {:2}'.format(n*1))
print('2  x ',n, ' = {:2}'.format(n*2))
print('3  x ',n, ' = {:2}'.format(n*3))
print('4  x ',n, ' = {:2}'.format(n*4))
print('5  x ',n, ' = {:2}'.format(n*5))
print('6  x ',n, ' = {:2}'.format(n*6))
print('7  x ',n, ' = {:2}'.format(n*7))
print('8  x ',n, ' = {:2}'.format(n*8))
print('9  x ',n, ' = {:2}'.format(n*9))
print('10 x ',n, ' = {:2}'.format(n*10))
print('-' * 18)
